### ISSUE TITLE
utils.ai.CreateTranscription (minor update) Add Response format inspector config field

### ISSUE THREAD

**Issue by DavidDurman** [clientIO/appmixer-connectors#230]
Sample flow:

![Image](https://github.com/user-attachments/assets/4380a552-5f89-46bc-862a-279336790405)

**Comment by RamBachkheti** [comment]
@vtalas: It looks like the connector is configured. 

Issue 1: Getting missing `apiKey` error while running the flow, please see the following image:
- ![Image](https://github.com/user-attachments/assets/a9c2749a-2e5f-4857-9ae9-b73216613d10)

Thanks!

**Comment by vtalas** [comment]
@RamBachkheti utils.ai is ready on stg.

**Comment by RamBachkheti** [comment]
Verified on staging: 
![Image](https://github.com/user-attachments/assets/862fe50d-fa02-4757-bc68-9abfe9d18c2d)
![Image](https://github.com/user-attachments/assets/054c8b4a-f498-4cb3-82eb-965a70259354)
